
project:
  name: quickstart-etleap-etl
  owner: quickstart-eng@amazon.com
  regions:
    - us-east-1
  s3_regional_buckets: true
  template: templates/etleap-vpc-master.yaml
tests:
  etleap-no-ha:
    parameters:
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      Subdomain: $[taskcat_random-string].etleap.com
    regions:
    - us-east-1
    template: templates/etleap-vpc-master.yaml