AWSTemplateFormatVersion: "2010-09-09"

Description: "Cloudformation template to spin up an Etleap deployment inside a VPC"

Parameters: 
  DeploymentId:
    Type: String
    Default: "test"
    Description: "The id of the deployment, provided by Etleap"
  VpcCidrBlock1:
    Type: Number
    Default: 10
    Description: "The first octet of the CIDR block of the desired VPC's address space"
  VpcCidrBlock2:
    Type: Number
    Default: 10
    Description: "The first octet of the CIDR block of the desired VPC's address space"
  FirstName:
    Type: String
    Default: "Caius"
  LastName:
    Type: String
    Default: "Brindescu"
  Email:
    Type: String
    Default: "caius@etleap.com"
  PublicKey:
    Type: String
    Default: ""
  ExternalZoneId:
    Type: String
    Default: "ZANDWKR8HMQO4"

Mappings: 
  RegionMap:
    us-east-1:
      app: "ami-00e34d9b0383c3821"
      nat: "ami-00a9d4a05375b2763"

Resources: 
  EtleapVPCStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        VpcCidrBlock1:
          Ref: VpcCidrBlock1
        VpcCidrBlock2:
          Ref: VpcCidrBlock2
        NatAMI: !FindInMap [RegionMap, !Ref "AWS::Region", nat]
      TemplateURL: ./infra/vpc.yaml
  
  EtleapSecretsStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: ./infra/secrets.yaml

  EtleapDBStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        VpcId: !GetAtt EtleapVPCStack.Outputs.VpcId
        SubnetA: !GetAtt EtleapVPCStack.Outputs.PrivateSubnetA
        SubnetB: !GetAtt EtleapVPCStack.Outputs.PrivateSubnetB  
      TemplateURL: ./infra/rds.yaml

  EtleapIAMStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: ./infra/iam.yaml

  EtleapKMSStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        EtleapAppRole: !GetAtt EtleapIAMStack.Outputs.EtleapAppRole
      TemplateURL: ./infra/kms.yaml
  
  EtleapAPPStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        VpcId: !GetAtt EtleapVPCStack.Outputs.VpcId
        VpcCidrBlock1: !Ref VpcCidrBlock1
        VpcCidrBlock2: !Ref VpcCidrBlock2
        DeploymentId: !Ref DeploymentId
        SubnetId: !GetAtt EtleapVPCStack.Outputs.PublicSubnetB
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", app]
        EtleapAppRole: !GetAtt EtleapIAMStack.Outputs.EtleapAppRole
        FirstName: !Ref FirstName
        LastName: !Ref LastName
        Email: !Ref Email
        KMSKey: !GetAtt EtleapKMSStack.Outputs.KMSKey
        EtleapDBSecurityGroup: !GetAtt EtleapDBStack.Outputs.EtleapDBSecurityGroup
        EtleapInternalSecurityGroup: !GetAtt EtleapVPCStack.Outputs.InternalSecurityGroup
      TemplateURL: ./infra/app.yaml
  
  EtleapEMRStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        DeploymentId: !Ref DeploymentId
        VpcId: !GetAtt EtleapVPCStack.Outputs.VpcId
        EtleapEMRRole: !GetAtt EtleapIAMStack.Outputs.EtleapEMRRole
        EtleapEMRInstanceProfile: !GetAtt EtleapIAMStack.Outputs.EtleapEMRInstanceProfile
        EtleapEMRDefaultRole: !GetAtt EtleapIAMStack.Outputs.EtleapEMRDefaultRole
        EtleapEMRAutoscalingDefaultRole: !GetAtt EtleapIAMStack.Outputs.EtleapEMRAutoscalingDefaultRole
        EtleapEMRSubnetId: !GetAtt EtleapVPCStack.Outputs.PrivateSubnetB
        EtleapInternalSecurityGroup: !GetAtt EtleapVPCStack.Outputs.InternalSecurityGroup
      TemplateURL: ./infra/emr.yaml

  EtleapRoute53Stack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        EMRMasterPublicDns: !GetAtt EtleapEMRStack.Outputs.EMRMasterPublicDns
        AppPublicIp: !GetAtt EtleapAPPStack.Outputs.EtleapAppIpAddres
        AppPrivateDns: !GetAtt EtleapAPPStack.Outputs.EtleapAppPrivateDns
        DBIp: !GetAtt EtleapDBStack.Outputs.Endpoint
        ExternalZoneId: !Ref ExternalZoneId
        VpcId: !GetAtt EtleapVPCStack.Outputs.VpcId
      TemplateURL: ./infra/r53.yaml

Outputs:
  EtleapSetupPassword:
    Value: !Sub '{{resolve:secretsmanager:EtleapSetupPassword:SecretString}}'
  EtleapLoginEmail:
    Value: !Ref Email