AWSTemplateFormatVersion: "2010-09-09"

Description: "Defines KMS keys"

Parameters:
  EtleapAppRole:
    Type: String

Resources:
  EtleapKMS:
    Type: "AWS::KMS::Key"
    Properties:
      Description: "Etleap secrets encryption key virginia region"
      Enabled: true
      KeyPolicy: 
        Version: 2012-10-17
        Id: 'etleap-kms-policy'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${EtleapAppRole}'
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
          - Sid: Allow attachment of persistent resources
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${EtleapAppRole}'
            Action:
              - 'kms:CreateGrant'
              - 'kms:ListGrants'
              - 'kms:RevokeGrant'
            Resource: '*'
            Condition:
              Bool:
                'kms:GrantIsForAWSResource': 'true'
      Tags:
        - Key: Name
          Value: "Etleap KMS"

Outputs:
  KMSKey:
    Value: !Ref EtleapKMS