AWSTemplateFormatVersion: "2010-09-09"

Description: "Cloudformation template to spin up a private VPC"

Parameters: 
  NatAMI:
    Type: String
    Description: "The AMI for the NAT instance"
  VpcID:
    Type: String
    Description: "The VPC this NAT lives in"

Resources:
  EtleapNATInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "m3.medium"
      ImageId: 
        Ref: NatAMI
      SecurityGroups:
        - String
      SubnetId: String
      Tags:
        - Name: "Etleap NAT"
      SourceDestinationCheck: False
      AssociatePublicIPAddress: True

  EtleapNapSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Etleap NAT"
      GroupName: "Etleap NAT"
      SecurityGroupEgress:
        - Egress
      SecurityGroupIngress:
        - Ingress
      Tags:
        - Name: "Etleap NAT"
      VpcId: String

Output:
  NatInstanceId:
    Value: !Ref EtleapNATInstance
