AWSTemplateFormatVersion: "2010-09-09"

Description: "Cloudformation template configure route 53 for internal DNS resolution"

Parameters:
  EMRMasterPublicDns:
    Type: String
  AppPublicIp:
    Type: String
  AppPrivateDns:
    Type: String
  DBIp:
    Type: String
  ExternalZoneId:
    Type: String
  VpcId:
    Type: String
  Subdomain:
    Type: String

Resources:
  EtleapPublicAppRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref ExternalZoneId
      Name: !Sub "app.${Subdomain}"
      ResourceRecords:
        - Ref: AppPublicIp
      TTL: '5'
      Type: 'A'

  EtleapRoute53Internal:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "etleap.internal"
      VPCs:
      - VPCId: !Ref VpcId
        VPCRegion: !Sub "${AWS::Region}"
  
  EtleapDBProdRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref EtleapRoute53Internal
      Name: "dbprod.etleap.internal." 
      ResourceRecords:
        - Ref: DBIp
      TTL: '60'
      Type: "CNAME"

  EtleapReadDBProdRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref EtleapRoute53Internal
      Name: "dbprod-read-replica.etleap.internal."
      ResourceRecords:
        - Ref: DBIp
      TTL: '60'
      Type: "CNAME"

  EtleapEMRRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref EtleapRoute53Internal
      Name: "emr.etleap.internal."
      ResourceRecords:
        - Ref: EMRMasterPublicDns
      TTL: '5'
      Type: "CNAME"

  EtleapAppRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref EtleapRoute53Internal
      Name: "app.etleap.internal."
      ResourceRecords:
        - Ref: AppPrivateDns
      TTL: '5'
      Type: "CNAME"
