AWSTemplateFormatVersion: "2010-09-09"

Description: "Creates an EC2 instance for Etleap's app node"

Parameters:
  DeploymentId:
    Type: String
  DeploymentSecret:
    Type: String
  DeploymentRole:
    Type: String
  InstanceProfile:
    Type: String
  ImageId:
    Type: String
  KeyPairName:
    Type: String
  InstanceName:
    Type: String
  SecurityGroup:
    Type: String
  SubnetId:
    Type: String
  EtleapDBRootPassword: 
    Type: String
  EtleapDBPassword: 
    Type: String
  EtleapDBSalesforcePassword: 
    Type: String
  EtleapAdminPassword:
    Type: String
  EtleapSetupPassword: 
    Type: String
  SelfSignedCertKey: 
    Type: String
  S3IntermediateBucket:
    Type: String
  S3IntermediateRole: 
    Type: String
  FirstName:
    Type: String
  LastName:
    Type: String
  Email:
    Type: String
  SetupPassword:
    Type: String
  KMSKey:
    Type: String
  MasterAppPrivateIp:
    Type: String
    Default: ""
  EMRHostname:
    Type: String
  RDSHostname:
    Type: String
  PublicHostnameOrIp:
    Type: String
    Default: ""
  MarketplacePurchase:
    Type: String

Conditions:
  IsSingleApp: !Equals [!Ref MasterAppPrivateIp, ""]

Resources:
  EtleapApp:
    Type: "AWS::EC2::Instance"
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref ImageId
      InstanceType: "t3.large"
      KeyName: !Ref KeyPairName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId: !Ref SubnetId
          GroupSet:
            - Ref: SecurityGroup
      Tags:
        - Key: Name
          Value: !Ref InstanceName
      UserData: !Base64
        "Fn::Sub":
          - |
            #cloud-config
            # -*- YAML -*-
            apt_upgrade: true
            locale: en_US.UTF-8

            write_files:
            - path: /home/ubuntu/.aws/config
              content: |
                [default]
                region = ${AWS::Region}
              owner: ubuntu:ubuntu
            - path: /root/.aws/config
              content: |
                [default]
                region = ${AWS::Region}
            - path: /home/ubuntu/ssl_certificate/ssl.pem
              content: |
                -----BEGIN CERTIFICATE-----
                MIIDEjCCAfoCCQCwU84b/lc2gjANBgkqhkiG9w0BAQsFADBLMQswCQYDVQQGEwJV
                UzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzEP
                MA0GA1UECgwGRXRsZWFwMB4XDTIwMDYwNTAxMDEzNVoXDTMwMDYwMzAxMDEzNVow
                SzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNVBAcMDVNh
                biBGcmFuY2lzY28xDzANBgNVBAoMBkV0bGVhcDCCASIwDQYJKoZIhvcNAQEBBQAD
                ggEPADCCAQoCggEBANbRtGKkwUY0LJ32u1p/lm0FcUnzCFP00o8Y3X10rB9j0kPF
                daKd+o1dIAfrD9FPjG/cZCRY0A2jGhngp/zQ9j8zMF0mUJX1q2Ub8yD6dDUL9KRW
                T3Zhr5h35T4FFcF6W/iiFT0L11xdSP6nsQFsKXan1ewp/RRCzXIx2mOyiQ7EkeaR
                k8meEQXWygk4y1ivfMrZdJQa8EnzMHrnPnSr/8HZB0DAjhXi+H4XcOgsVD8Fjbcj
                0BRk12YP278lcygekVYndr9YTvphKBBlTeVPqSrWzFIJV7e/9PR9NGyOga2A6dQ2
                ZGvvLZ0KK9ivAh7Hxatk+TjxFtvqWKKORAR19c8CAwEAATANBgkqhkiG9w0BAQsF
                AAOCAQEABaGzI5PVlrIkG/RVY/5IQYKN6Wm09FhDA6ocFCDKW0C9lf28GSximxEW
                KTH/DB/FyTK19y7UygM4Qw9eknFT7oNlZABd4fvBjBHwxfNNd53IOaEVn56As8jv
                g2jExvgv7/i62K2KE1zXI0P8SoOLyWXiYlo2uvyLzv21dNBWRAyOd9cpNndq7YsK
                qqWW0jUyL1dpytJ4Czw8O+1UiAP3oK61k1hepZMPtrdKUZIbhGNnoCiZrfkb715Q
                c04YhqhUzaCmm+Ui1KxJfGrheLNind0YV3udwdMAHVQninKvTCC0Rp5SwrwvC72x
                IdrMAzUSKCQ8sKWUzcq8ddquBFP9nA==
                -----END CERTIFICATE-----
              owner: ubuntu:ubuntu
            - path: /home/ubuntu/db-init.sh
              content: |
                #!/bin/bash -e

                DB_ROOT_PASSWORD=$1
                ETLEAP_DB_PASSWORD=$2
                SALESFORCE_DB_PASSWORD=$3
                ORG_NAME=$4

                mysql -h$ETLEAP_RDS_HOSTNAME -uroot -p$DB_ROOT_PASSWORD <<EOF
                CREATE DATABASE IF NOT EXISTS etleap;
                GRANT ALL PRIVILEGES ON etleap.* TO 'etleap-prod'@'%' IDENTIFIED BY "$ETLEAP_DB_PASSWORD";

                CREATE DATABASE IF NOT EXISTS salesforce;
                USE salesforce;
                GRANT ALL PRIVILEGES ON salesforce.* TO 'salesforce'@'%' IDENTIFIED BY "$SALESFORCE_DB_PASSWORD";
                CREATE TABLE IF NOT EXISTS jobs (id bigint(20) NOT NULL AUTO_INCREMENT,
                  user_hash varchar(64) NOT NULL,
                  job_id varchar(64) NOT NULL,
                  first_batch_id varchar(64),
                  query_hash varchar(64) NOT NULL,
                  bulk_api_calls int(11) NOT NULL,
                  failed tinyint(1) NOT NULL DEFAULT 0,
                  create_date datetime NOT NULL,
                  PRIMARY KEY (id),
                  UNIQUE KEY (user_hash, job_id),
                  INDEX user_hash_create_date (user_hash, create_date)
                ) ENGINE=InnoDB;

                FLUSH PRIVILEGES;

                EOF

                exit 0
              owner: ubuntu:ubuntu
              permissions: "0755"
            - path: /home/ubuntu/.etleap
              content: |
                export CUSTOMER_VPC=1
                export ETLEAP_DEPLOYMENT_ID=${DeploymentId}
                export USE_PROD_SECRETS=0
                export JOB_ROLE=customer_job,monitor
                export ETLEAP_DB_PASSWORD="$(aws secretsmanager get-secret-value --secret-id ${EtleapDBPassword} | jq -r .SecretString)"
                export SALESFORCE_DB_PASSWORD="$(aws secretsmanager get-secret-value --secret-id ${EtleapDBSalesforcePassword} | jq -r .SecretString)"
                export ETLEAP_HOSTS_ALLOWED="${PublicHostnameOrIp}"
                export FRONT_END_HOSTNAME="${PublicHostnameOrIp}"
                export ETLEAP_FRONT_END_URL="https://${PublicHostnameOrIp}/"
                export ETLEAP_CORS_ALLOWED_ORIGINS="https://${PublicHostnameOrIp}"
                export API_HOSTNAME="${PublicHostnameOrIp}"
                export API_URL="https://$API_HOSTNAME/"
                export ETLEAP_BASE_URL=$API_URL
                export ETLEAP_CONF_FILE=/opt/etleap/prod-customervpc.conf
                export ETLEAP_HTTP_SESSION_DOMAIN="${PublicHostnameOrIp}"
                export ETLEAP_KMS_KEY_VIRGINIA="${KMSKey}"
                export ETLEAP_SETUP_FIRST_NAME="${FirstName}"
                export ETLEAP_SETUP_LAST_NAME="${LastName}"
                export ETLEAP_SETUP_EMAIL="${Email}"
                export ETLEAP_SETUP_PASSWORD="${EtleapSetupPassword}"
                export ETLEAP_SETUP_ADMIN_PASSWORD="$(aws secretsmanager get-secret-value --secret-id ${EtleapAdminPassword} | jq -r .SecretString)"
                export ETLEAP_SETUP_INTERMEDIATE_BUCKET=${S3IntermediateBucket}
                export ETLEAP_SETUP_INTERMEDIATE_ROLE_ARN="${S3IntermediateRole}"
                export ENABLE_YSJES='true'
                export ETLEAP_DEPLOYMENT_ROLE="${DeploymentRole}"
                export ETLEAP_SECRET_APPLICATION_SECRET="$(aws secretsmanager get-secret-value --secret-id ${DeploymentSecret} | jq -r .SecretString)"
                export ETLEAP_RDS_HOSTNAME="${RDSHostname}"
                export ETLEAP_EMR_HOSTNAME="${EMRHostname}"
                export ETLEAP_YSJES_HOSTNAME="${MasterAppPrivateIp}"
                export ETLEAP_MAIN_APP_IP="${MasterAppPrivateIp}"
                export MARKETPLACE_DEPLOYMENT="${MarketplacePurchase}"
              owner: ubuntu:ubuntu
            
            runcmd:
            - aws configure set region `curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region`
            - aws secretsmanager get-secret-value --secret-id ${SelfSignedCertKey} | jq -r .SecretString > /home/ubuntu/ssl_certificate/ssl.key && chown ubuntu:ubuntu /home/ubuntu/ssl_certificate/ssl.key
            - 'sed -i ''s/"dns": \[".*"\]/"dns": ["169.254.169.253"]/g'' /etc/docker/daemon.json'
            - service docker restart
            - /home/ubuntu/db-init.sh $(aws secretsmanager get-secret-value --secret-id ${RootDBPassword} | jq -r .SecretString) $(aws secretsmanager get-secret-value --secret-id ${EtleapDBPassword} | jq -r .SecretString) $(aws secretsmanager get-secret-value --secret-id ${EtleapDBSalesforcePassword} | jq -r .SecretString) ${DeploymentId}
            - yes | ssh-keygen -f /home/ubuntu/.ssh/id_rsa -N ''
            - cat /home/ubuntu/.ssh/id_rsa.pub >> /home/ubuntu/.ssh/authorized_keys
            - su ubuntu -c ". /home/ubuntu/.etleap && /home/ubuntu/cron-deploy-customervpc.sh"
          - RootDBPassword: !Ref EtleapDBRootPassword
            EtleapDBPassword: !Ref EtleapDBPassword
            EtleapDBSalesforcePassword: !Ref EtleapDBSalesforcePassword
            EtleapAdminPassword: !Ref EtleapAdminPassword
            EtleapSetupPassword: !Ref SetupPassword
            SelfSignedCertKey: SelfSignedCertificateKey
            S3IntermediateRole: !Ref S3IntermediateRole
            DeploymentSecret: !Ref DeploymentSecret
            RDSHostname: !Ref RDSHostname
            MasterAppPrivateIp: !If [IsSingleApp, "127.0.0.1", !Ref MasterAppPrivateIp]
            EMRHostname: !Ref EMRHostname
            PublicHostnameOrIp: !If [IsSingleApp, "$(curl http://169.254.169.254/latest/meta-data/public-ipv4)", !Ref PublicHostnameOrIp]
            MarketplacePurchase: !Ref MarketplacePurchase

Outputs:
  PublicIp:
    Value: !GetAtt EtleapApp.PublicIp
  PrivateIp:
    Value: !GetAtt EtleapApp.PrivateIp
  PrivateDnsName:
    Value: !GetAtt EtleapApp.PrivateDnsName
  Instance:
    Value: !Ref EtleapApp