AWSTemplateFormatVersion: "2010-09-09"

Description: "Cloudformation template to spin up an Etleap deployment inside a VPC (qs-1qqblr2nf)"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network configuration
      Parameters:
      - VpcCidrBlock1
      - VpcCidrBlock2
      - AllowedIPCidr
    - Label:
        default: Domain configuration
      Parameters:
      - ExternalZoneId
      - Subdomain
    - Label:
        default: ETLeap configuration
      Parameters:
      - KeyPairName
      - DeploymentId
      - FirstName
      - LastName
      - Email
      - SetupPassword
    - Label:
        default: AWS Quick Start configuration
      Parameters:
      - QSS3BucketName
      - QSS3BucketRegion
      - QSS3KeyPrefix
    ParameterLabels:
      DeploymentId:
        default: Deployment ID
      KeyPairName:
        default: Key pair name
      VpcCidrBlock1:
        default: VPC CIDR block 1
      VpcCidrBlock2:
        default: VPC CIDR block 2
      FirstName:
        default: First name
      LastName:
        default: Last name
      Email:
        default: Email address
      SetupPassword:
        default: Etleap initial login password
      ExternalZoneId:
        default: External zone ID
      Subdomain:
        default: Subdomain
      AllowedIPCidr:
        default: Allowed IP CIDR block
      QSS3BucketName:
        default: Quick Start S3 Bucket Name
      QSS3BucketRegion:
        default: Quick Start S3 bucket region
      QSS3KeyPrefix:
        default: Quick Start S3 Key Prefix
Parameters: 
  DeploymentId:
    Type: String
    Default: "test"
    Description: "The id of the deployment, provided by Etleap"
  VpcCidrBlock1:
    Type: Number
    Default: 10
    Description: "The first octet of the CIDR block of the desired VPC's address space"
  VpcCidrBlock2:
    Type: Number
    Default: 10
    Description: "The second octet of the CIDR block of the desired VPC's address space"
  FirstName:
    Type: String
    Default: "Caius"
    Description: "User first name"
  LastName:
    Type: String
    Default: "Brindescu"
    Description: "User last name"
  Email:
    Type: String
    Default: "caius@etleap.com"
    Description: "User email address"
  SetupPassword:
    Type: String
    Default: "test1234"
    Description: "Etleap initial login password"
  
  ExternalZoneId:
    Type: String
    Default: "ZANDWKR8HMQO4"
    Description: "Zone ID for the Route 53 hosted zone"
  Subdomain:
    Type: String
    Default: "dev.etleap.com"
    Description: "Subdomain to be created in the Route 53 hosted zone"
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: EtleapCFTest
    Description: "EC2 key pair name"
  AllowedIPCidr:
    Type: String
    Default: "0.0.0.0/0"
    Description: "CIDR block allowed remote access to the environment"
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription:
      Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description:
      S3 bucket name for the Quick Start assets. Quick Start bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.'
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription:
      Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-etleap-etl/
    Description:
      S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String

Mappings: 
  RegionMap:
    us-east-1:
      app: ami-077d276f0a7a24f4b
      mp-app: ami-039c1ccd1b77386ad
      nat: ami-00a9d4a05375b2763
    us-east-2:
      mp-app: ami-025efaa4b727d0607
      nat: ami-00d1f8201864cc10c
    us-west-1:
      mp-app: ami-08f54ac5ecc1d06a2
      nat: ami-097ad469381034fa2
    us-west-2:
      mp-app: ami-0cadbaa3ea2314081
      nat: ami-0b840e8a1ce4cdf15
    ca-central-1:
      mp-app: ami-06af9d994f087da1d
      nat: ami-0b32354309da5bba5
    eu-central-1:
      mp-app: ami-095335b26e0c90e50
      nat: ami-06a5303d47fbd8c60
    eu-west-1:
      mp-app: ami-0ef993d4852ba2af0
      nat: ami-024107e3e3217a248
    eu-west-2:
      mp-app: ami-063ff5c69f26e9741
      nat: ami-0ca65a55561666293
    eu-west-3:
      mp-app: ami-0c940e189e77ff4c1
      nat: ami-0641e4dfc1427f114
    ap-southeast-1:
      mp-app: ami-0052afd32691a33ae
      nat: ami-01514bb1776d5c018
    ap-southeast-2:
      mp-app: ami-0151db4f4715bf4e8
      nat: ami-062c04ec46aecd204
    ap-south-1:
      mp-app: ami-00d28db51fd7d5221
      nat: ami-00b3aa8a93dd09c13
    ap-northeast-1:
      mp-app: ami-0a8a2772fd2a47d2b
      nat: ami-00d29e4cb217ae06b
    ap-northeast-2:
      mp-app: ami-01b597bf1591b9676
      nat: ami-0d98591cbf9ef1ffd
    sa-east-1:
      mp-app: ami-0899953081bebdc04
      nat: ami-057f5d52ff7ae75ae
    eu-north-1:
      mp-app: ami-0b12307dbcbaf7da6
      nat: ami-28d15f56
    ap-east-1:
      mp-app: ami-01901a73a22b53a96
      nat: ami-0c6ed192398e5636d
    me-south-1:
      mp-app: ami-04de93c7f1c75f57d
      nat: ami-0e9909371b18e2ec7
    af-south-1:
      mp-app: ami-08806b5a836d14831
      nat: ami-0f7b1b7c2c50e3202
    eu-south-1:
      mp-app: ami-02ebc44cb1930489c
      nat: ami-08df23351dd5626cf

Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']

Resources: 
  EtleapVPCStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        VpcCidrBlock1:
          Ref: VpcCidrBlock1
        VpcCidrBlock2:
          Ref: VpcCidrBlock2
        NatAMI: !FindInMap [RegionMap, !Ref "AWS::Region", nat]
      TemplateURL: 
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/vpc.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
  
  EtleapSecretsStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: 
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/secrets.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
  
  EtleapRoute53Stack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        VpcId: !GetAtt EtleapVPCStack.Outputs.VpcId
      TemplateURL: 
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/r53.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]

  EtleapDBStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        VpcId: !GetAtt EtleapVPCStack.Outputs.VpcId
        SubnetA: !GetAtt EtleapVPCStack.Outputs.PrivateSubnetA
        SubnetB: !GetAtt EtleapVPCStack.Outputs.PrivateSubnetB  
        Route53Zone: !GetAtt EtleapRoute53Stack.Outputs.Route53Zone
      TemplateURL: 
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/rds.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]

  EtleapIAMStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        DeploymentId: !Ref DeploymentId
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/iam.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]

  EtleapKMSStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        EtleapAppRole: !GetAtt EtleapIAMStack.Outputs.EtleapAppRole
      TemplateURL: 
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/kms.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
  
  EtleapAPPStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: EtleapDBStack
    Properties:
      Parameters:
        KeyPairName: !Ref KeyPairName
        VpcId: !GetAtt EtleapVPCStack.Outputs.VpcId
        VpcCidrBlock1: !Ref VpcCidrBlock1
        VpcCidrBlock2: !Ref VpcCidrBlock2
        DeploymentId: !Ref DeploymentId
        SubnetId: !GetAtt EtleapVPCStack.Outputs.PublicSubnetB
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", app]
        EtleapAppRole: !GetAtt EtleapIAMStack.Outputs.EtleapAppRole
        FirstName: !Ref FirstName
        LastName: !Ref LastName
        Email: !Ref Email
        SetupPassword: !Ref SetupPassword
        KMSKey: !GetAtt EtleapKMSStack.Outputs.KMSKey
        EtleapDBSecurityGroup: !GetAtt EtleapDBStack.Outputs.EtleapDBSecurityGroup
        EtleapInternalSecurityGroup: !GetAtt EtleapVPCStack.Outputs.InternalSecurityGroup
        AllowedIPCidr: !Ref AllowedIPCidr
        Route53Zone: !GetAtt EtleapRoute53Stack.Outputs.Route53Zone
        ExternalZoneId: !Ref ExternalZoneId
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/app.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
  
  EtleapEMRStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        DeploymentId: !Ref DeploymentId
        VpcId: !GetAtt EtleapVPCStack.Outputs.VpcId
        EtleapEMRRole: !GetAtt EtleapIAMStack.Outputs.EtleapEMRRole
        EtleapEMRInstanceProfile: !GetAtt EtleapIAMStack.Outputs.EtleapEMRInstanceProfile
        EtleapEMRDefaultRole: !GetAtt EtleapIAMStack.Outputs.EtleapEMRDefaultRole
        EtleapEMRAutoscalingDefaultRole: !GetAtt EtleapIAMStack.Outputs.EtleapEMRAutoscalingDefaultRole
        EtleapEMRSubnetId: !GetAtt EtleapVPCStack.Outputs.PrivateSubnetB
        EtleapInternalSecurityGroup: !GetAtt EtleapVPCStack.Outputs.InternalSecurityGroup
        Route53Zone: !GetAtt EtleapRoute53Stack.Outputs.Route53Zone
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/emr.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]

Outputs:
  EtleapSetupPassword:
    Value: !Ref SetupPassword
  EtleapLoginEmail:
    Value: !Ref Email