AWSTemplateFormatVersion: "2010-09-09"

Description: "Cloudformation template configure route 53 for internal DNS resolution"

Parameters:
  VpcId:
    Type: String

Resources:
  EtleapRoute53Internal:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "etleap.internal"
      VPCs:
      - VPCId: !Ref VpcId
        VPCRegion: !Sub "${AWS::Region}"
  
Outputs:
  Route53Zone:
    Value: !Ref EtleapRoute53Internal