AWSTemplateFormatVersion: "2010-09-09"

Description: "Creates an RDS instance."

Parameters:
  VpcId:
    Type: String
  SubnetA:
    Type: String
  SubnetB:
    Type: String
  DeploymentOption:
    Type: String

Conditions:
  IsHighAvailability: !Equals [!Ref DeploymentOption, "High Availability"]

Resources: 
  EtleapDBRootPassword:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Join ["-", [EtleapDBRootPassword, !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref "AWS::StackId"]]]]]]
      GenerateSecretString:
        ExcludePunctuation: true
        PasswordLength: 20

  EtleapDB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: "500"
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      BackupRetentionPeriod: 7
      DBInstanceClass: "db.m5.large"
      DBInstanceIdentifier: !Join ["-", [etleap-db, !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref "AWS::StackId"]]]]]]
      DBParameterGroupName: !Ref "EtleapDBParameterGroup"
      DBSubnetGroupName: !Ref "EtleapDBSubnetGroup"
      DeletionProtection: false
      EnablePerformanceInsights: true
      Engine: "mysql"
      EngineVersion: "5.6.41"
      MasterUsername: root
      MasterUserPassword: !Sub 
        - "{{resolve:secretsmanager:${EtleapDBRootPassword}}}"
        - EtleapDBRootPassword: !Join ["-", [EtleapDBRootPassword, !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref "AWS::StackId"]]]]]]
      StorageEncrypted: true
      StorageType: "gp2"
      MultiAZ: !If [IsHighAvailability, "true", "false"]
      VPCSecurityGroups:
        - Ref: EtleapDBSecurityGroup

  EtleapDBParameterGroup:
    Type: "AWS::RDS::DBParameterGroup"
    Properties:
      Description: "MySQL 5.6 with Etleap modifications"
      Family: "mysql5.6"
      Parameters:
        character-set-client-handshake: "0"
        collation_server: latin1_swedish_ci
        character_set_server: latin1
        log_bin_trust_function_creators: "1"
        binlog_format: ROW
        innodb_lock_wait_timeout: "250"
        general_log: "0"
        long_query_time: "0.05"
        slow_query_log: "1"
        log_warnings: "2"
        log_output: file
        binlog_checksum: none
    
  EtleapDBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "Etleap DB Subnet Group"
      DBSubnetGroupName: !Join ["-", [Etleap-DB, !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref "AWS::StackId"]]]]]]
      SubnetIds: 
        - Ref: SubnetA
        - Ref: SubnetB

  EtleapDBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Etleap DB"
      GroupName: !Join ["-", [Etleap-DB, !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref "AWS::StackId"]]]]]]
      Tags:
        - Key: Name
          Value: "Etleap DB"
      VpcId: !Ref VpcId

Outputs:
  Endpoint:
    Value: !GetAtt EtleapDB.Endpoint.Address
  EtleapDBSecurityGroup:
    Value: !Ref EtleapDBSecurityGroup
  EtleapDBRootPassword:
    Value: !Ref EtleapDBRootPassword